name:Upload Website
on: 
push:
 branches:
 -main

 jobs
 deploy:
 build-and-deploy:
 steps:
  runs-on:ubntu-latest
 -name: Checkout
 uses: actions/checkout@v1

 -name: Configure AWS Credentials
 uses: aws-actions/configure-aws credentials@v1
 with:
 aws-access-key-id:${{secrets.AWS_ACCESS_KEY_ID}}
 aws-secret-access-key:${{secret.AWS_SECRET_ACCESS_KEY}}
 aws-region: us-east-1

 -name: Deploy static site to s3 bucket
 
 
  

